version: "3"
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    working_dir: /app
    volumes:
      - ./client:/app/client:cached
      - node_modules:/app/client/node_modules
    ports:
      - 5173:5173
    command: yarn dev

volumes:
  node_modules:
